### ISSUE TITLE
Failed to create player model for default

### ISSUE THREAD

**Issue by ManicZ0mb13** [Alexthw46/Ars-Elementals#53]
I downloaded this modpack "Luvstar's Fairycore" which works fine, later, I downloaded some other mods that weren't in the modpack, which worked fine until I downloaded Ars Elemental. When I add Ars Elemental it crashes but when I remove it the game is fine. In the crash report, where the mod list is, everything else says COMMON_SET except for Ars Elemental, which says ERROR.
[crash-2024-02-08_23.35.03-client.txt](https://github.com/Alexthw46/Ars-Elemental/files/14217534/crash-2024-02-08_23.35.03-client.txt)

**Comment by Alexthw46** [comment]
Idk but the log points to this as the error first, maybe you should crosspost this to midnight dust or whatever the mod is called? If it's still my problem at least maybe they have an idea on why their mod errors

Caused by: java.lang.IllegalArgumentException: No model for layer midnight-hats:witch_hat#main
	at net.minecraft.client.model.geom.EntityModelSet.m_171103_(EntityModelSet.java:17) ~[client-1.19.2-20220805.130853-srg.jar%23349!/:?] {re:mixin,re:classloading}
	at eu.midnightdust.hats.witch.WitchHatFeatureRenderer.<init>(WitchHatFeatureRenderer.java:43) ~[midnightlib-forge-1.0.0.jar%23309!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.handler$cci000$addFeatures(PlayerRenderer.java:3022) ~[client-1.19.2-20220805.130853-srg.jar%23349!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.<init>(PlayerRenderer.java:56) ~[client-1.19.2-20220805.130853-srg.jar%23349!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRenderers.m_174097_(EntityRenderers.java:24) ~[client-1.19.2-20220805.130853-srg.jar%23349!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.renderer.entity.EntityRenderers.m_234604_(EntityRenderers.java:169) ~[client-1.19.2-20220805.130853-srg.jar%23349!/:?] {re:classloading,pl:accesstransformer:B}
	... 134 more

**Comment by ManicZ0mb13** [comment]
Midnight Dust is the team that created MidnightLib. Apparently the issue was that there was no Forge version for 1.19.2 which only crashed when ars elemental was added. After i deleted it, i got another crash error saying that ars elemental didn't load, so i just redownload ars nouveau and that fixed the issue, thank you.
