### ISSUE TITLE
[1.19.2] Fail to load on new Ars update

### ISSUE THREAD

**Issue by ffuentesm** [Alexthw46/Ars-Elementals#9]
the new Ars update (ars_nouveau-1.19.2-3.4.5.jar) causes Elemental to fail to load.
![image](https://user-images.githubusercontent.com/44974827/198186920-91d897ec-82b9-47c8-969a-d91adf47fa74.png)

Log: https://pastebin.com/QYHKx7EG

**Comment by Zelioth** [comment]
can confirm this issue is present in the latest update of 1.19.2 Ars Elemental. Haven't found a fix yet

**Comment by Zelioth** [comment]
[latest.log](https://github.com/Alexthw46/Ars-Elemental/files/9875656/latest.log)
[crash-2022-10-26_22.57.02-fml.txt](https://github.com/Alexthw46/Ars-Elemental/files/9875660/crash-2022-10-26_22.57.02-fml.txt)

**Comment by Zelioth** [comment]
Update, the issue doesn't seem to be Ars Elemental even though it does reference it in the crash. I have discovered that it is another mod causing the error. I have not found what mod yet but I am testing now and will give results once found

**Comment by Zelioth** [comment]
Updating Ars Nouveau to version 3.4.5 causes Ars Elemental to throw this error. downgrading Ars Nouveau back to 3.4.3 fixes the error and allows you to update to the newest version of Ars Elemental

**Comment by Zelioth** [comment]
Updating my mod pack I have all of the "ars" mods. Updating Ars Nouveau to version 3.4.5 appears to cause an error on load in but the error is blamed on Ars Elemental. After testing I updated both Ars Elemental to it's newest version, and Ars Nouveau. The error is given. When downgrading ONLY Ars Nouveau the error goes away and the mod pack load correctly with no issue. So this issue appears to be within Ars Nouveau Update 3.4.5 even though the crash report references 

Caused by 0: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.1.47.jar%23562!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.47.jar%23561!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

After further testing it appears that just updating Ars Nouveau breaks any version of Ars Elemental.

**Comment by Alexthw46** [comment]
update for 1.19.2 is now on curseforge
